# Generated by Django 3.2.7 on 2021-09-12 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Course', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='enrollment',
            field=models.ManyToManyField(blank=True, to='Course.course'),
        ),
        migrations.AlterField(
            model_name='course',
            name='status',
            field=models.CharField(max_length=20),
        ),
    ]
